Use entity guid instead of table uri for Atlas part
L-KID/amundsenmetadatalibrary pull request #1
Opened 2019-06-03 15:08 UTC by L-KID

### Summary of Changes

Use entity guid instead of table uri. Finished Atlas part. To do FrontEnd and Neo4j.

### Tests

Modified test_atlas_proxy to test using of entity guid.

2019-06-03 15:28 UTC, verdan commented
Nice. few things. 
- Please make sure to revert the config settings. 
- Secondly, I think it would be unfair to use the word `guid`. can we please rename that to only id? `table_id`, `column_id` ? 
- Last, I think Neo4j does not use id for their operations, as they are not persistent. (not 100% sure, need to check). But, we should make this change incrementally otherwise, to make it work for both neo4j and atlas.

2019-06-04 20:00 UTC, verdan requested changes
@L-KID nice work!! we still need to think of neo4j proxy.

2019-06-04 20:00 UTC, verdan commented on tests/unit/proxy/test_atlas_proxy.py
> +            'guid': 'ff6f8097-aead-428a-94ca-3fcb92b02255',
can we please revert it and make it simple integer ? That would be really easy to test and compare.

2019-06-05 12:33 UTC, L-KID commented on tests/unit/proxy/test_atlas_proxy.py
> +            'guid': 'ff6f8097-aead-428a-94ca-3fcb92b02255',
Okay, of course. But I'm also thinking to make it a bit more real using those mock guid.

2019-06-05 12:38 UTC, merged